version: '3.1' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: gnar-app # specify the directory of the Dockerfile
    volumes:
      - ./gnar-app:/usr/src/app
    ports:
      - "4200:4200" # specify port forewarding

  express: #name of the second service
    build: gnar-server # specify the directory of the Dockerfile
    volumes:
      - ./gnar-server:/usr/src/app
    secrets:
      - nexmo-key
      - nexmo-secret
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forewarding

secrets:
  nexmo-key:
    file: /gnar_conf/.secrets/NEXMO_KEY
  nexmo-secret:
    file: /gnar_conf/.secrets/NEXMO_SECRET