version: '3.1' # specify docker-compose version

# Define the services/containers to be run
services:
  # angular: # app
  #   build: gnar-app # specify the directory of the Dockerfile
  #   volumes:
  #     - ./gnar-app:/usr/src/app
  #   ports:
  #     - "4200:4200" # specify port forewarding

  # database: # mongodb
  #   image: mongo # specify image to build container from
  #   ports:
  #     - "27017:27017" # specify port forewarding

  express: # server
    build: gnar-server # specify the directory of the Dockerfile
    volumes:
      - ./gnar-server:/usr/src/app
    secrets:
      - nexmo-key
      - nexmo-secret
      - mongo-user
      - mongo-password
    ports:
      - "3000:3000" #specify ports forewarding
    links:
      - redis # link this service to the redis service

  redis: # redis
    image: redis
    ports:
        - "6379:6379" # specify port forewarding

secrets:
  nexmo-key:
    file: /gnar_conf/.secrets/NEXMO_KEY
  nexmo-secret:
    file: /gnar_conf/.secrets/NEXMO_SECRET
  mongo-user:
    file: /gnar_conf/.secrets/MONGO_USER
  mongo-password:
    file: /gnar_conf/.secrets/MONGO_PASSWORD